package com.sample.rules
 
import com.sample.Message;
 
rule "Hello World"
    when
        $m : Message( status == Message.HELLO, $myMessage : message )
    then
        System.out.println( $myMessage );
        $m.setMessage( "Goodbye!" );
        $m.setStatus( Message.GOODBYE );
        update( $m );
        
        Message again = new Message();
        again.setMessage( "Goodbye again!" );
        again.setStatus( Message.GOODBYE );
        insert(again);
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, $myMessage : message )
    then
        System.out.println( $myMessage );
end
