//created on: 28.02.2018
package com.sample.states

import com.sample.State;

//declare type State
//    @propertyChangeSupport
//end
 
rule Bootstrap
    when
        a : State(name == "A", state == State.NOTRUN )
    then
        System.out.println(a.getName() + " finished" );
        a.setState( State.FINISHED );
        update(a);
end

 
rule "A to B"
    when
        State(name == "A", state == State.FINISHED )
        b : State(name == "B", state == State.NOTRUN )
        d : State(name == "D", state == State.NOTRUN )
    then
        System.out.println(b.getName() + " finished" );
        b.setState( State.FINISHED );
        //delete(d);
        update(b);
end

rule "B to D"
    enabled false
    salience 50
    when
        State(name == "B", state == State.FINISHED )
        d : State(name == "D", state == State.NOTRUN )
    then
        System.out.println(d.getName() + " finished" );
        modify(d){setState( State.FINISHED );}
end


rule "B to C"
    salience 10
    when
        State(name == "B", state == State.FINISHED )
        c : State(name == "C", state == State.NOTRUN )
    then
        System.out.println(c.getName() + " finished" );
        modify(c){setState( State.FINISHED );}
end

